version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_DB: "****"
      POSTGRES_USER: "****"
      POSTGRES_PASSWORD: "****"
    ports:
      - 5432:5432
  nextjs:
    build: ./
  nginx:
    build: ./nginx
    ports:
      - 8080:8080
